name: ashub_chatai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  heroicons: ^0.9.0
  eva_icons_flutter: ^3.0.0
  iconsax: ^0.0.8
  flutter_screenutil :
  flutter_animate: ^4.2.0
  animations: ^2.0.7
  http: ^1.4.0
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  lottie: ^3.1.2
  flutter_markdown: ^0.6.14
  highlight: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

# -----------------------------------
# Launcher icon configuration
# Run: flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
